export type Language = 'english' | 'code' | 'quotes' | 'tharoor' | 'abusive' | 'potter-head';

export const CODE_WORDS = [
  "const", "let", "var", "function", "return", "if", "else", "for", "while",
  "do", "switch", "case", "break", "continue", "class", "extends", "interface",
  "type", "enum", "import", "export", "default", "from", "as", "async", "await",
  "try", "catch", "finally", "throw", "new", "delete", "typeof", "instanceof",
  "void", "null", "undefined", "true", "false", "this", "super", "static",
  "public", "private", "protected", "readonly", "string", "number", "boolean",
  "object", "array", "any", "never", "unknown", "push", "pop", "map", "filter",
  "reduce", "forEach", "find", "splice", "slice", "concat", "join", "length",
  "keys", "values", "entries", "fetch", "then", "resolve", "reject", "promise",
  "console", "log", "error", "warn", "props", "state", "ref", "event", "data",
  "index", "value", "key", "name", "id", "list", "item", "node", "result",
  "response", "request", "config", "options", "handler", "component", "render",
  "update", "create", "delete", "read", "write", "parse", "format", "validate",
  "merge", "split", "trim", "replace", "match", "test", "exec", "sort",
  "reverse", "flat", "fill", "from", "set", "get", "has", "size", "clear",
  "callback", "arrow", "scope", "closure", "prototype", "method", "property",
  "module", "require", "package", "version", "install", "build", "run", "start",
  "index", "route", "path", "query", "body", "header", "status", "message",
];

export const QUOTES = [
  "the only way to do great work is to love what you do",
  "in the middle of every difficulty lies opportunity",
  "it does not matter how slowly you go as long as you do not stop",
  "life is what happens to you while you are busy making other plans",
  "the future belongs to those who believe in the beauty of their dreams",
  "tell me and I forget teach me and I remember involve me and I learn",
  "you miss one hundred percent of the shots you do not take",
  "whether you think you can or you think you cannot you are right",
  "I have not failed I have just found ten thousand ways that will not work",
  "an unexamined life is not worth living",
  "spread love everywhere you go let no one ever come to you without leaving happier",
  "when you reach the end of your rope tie a knot in it and hang on",
  "do not go where the path may lead go instead where there is no path and leave a trail",
  "the greatest glory in living lies not in never falling but in rising every time we fall",
  "in the end it is not the years in your life that count it is the life in your years",
  "never let the fear of striking out keep you from playing the game",
  "life is either a daring adventure or nothing at all",
  "many of life's failures are people who did not realize how close they were to success when they gave up",
  "you have brains in your head you have feet in your shoes you can steer yourself any direction you choose",
  "if life were predictable it would cease to be life and be without flavor",
  "if you look at what you have in life you will always have more",
  "if you set your goals ridiculously high and it is a failure you will fail above everyone else's success",
  "life is not measured by the number of breaths we take but by the moments that take our breath away",
  "if you want to live a happy life tie it to a goal not to people or things",
  "never let the fear of striking out keep you from playing the game",
  "money and success don't change people they merely amplify what is already there",
  "your time is limited so don't waste it living someone else's life",
  "not how long but how well you have lived is the main thing",
  "if life is a journey then let your passion be the engine and your values be the map",
];

export const WORD_LIST = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
  "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
  "but", "his", "by", "from", "they", "we", "say", "her", "she", "or",
  "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know",
  "take", "people", "into", "year", "your", "good", "some", "could",
  "them", "see", "other", "than", "then", "now", "look", "only", "come",
  "its", "over", "think", "also", "back", "after", "use", "two", "how",
  "our", "work", "first", "well", "way", "even", "new", "want", "because",
  "any", "these", "give", "day", "most", "us", "great", "between", "need",
  "large", "often", "hand", "high", "place", "hold", "turn", "help",
  "press", "word", "house", "point", "city", "play", "small", "number",
  "off", "always", "next", "food", "keep", "children", "feet", "land",
  "side", "without", "boy", "once", "animal", "life", "enough", "took",
  "four", "head", "above", "kind", "began", "almost", "live", "page",
  "got", "earth", "need", "far", "hand", "high", "place", "found",
  "study", "still", "learn", "plant", "cover", "food", "sun", "four",
  "thought", "let", "keep", "eye", "never", "last", "door", "between",
  "city", "tree", "cross", "since", "hard", "start", "might", "story",
  "saw", "far", "sea", "draw", "left", "late", "run", "dont", "while",
  "press", "close", "night", "real", "life", "few", "north", "open",
  "seem", "together", "next", "white", "children", "begin", "got", "walk",
  "example", "ease", "paper", "group", "always", "music", "those", "both",
  "mark", "book", "letter", "until", "mile", "river", "car", "feet",
  "care", "second", "enough", "plain", "girl", "usual", "young", "ready",
  "above", "ever", "red", "list", "though", "feel", "talk", "bird",
  "soon", "body", "dog", "family", "direct", "pose", "leave", "song",
  "measure", "door", "product", "black", "short", "numeral", "class",
  "wind", "question", "happen", "complete", "ship", "area", "half",
  "rock", "order", "fire", "south", "problem", "piece", "told", "knew",
  "pass", "since", "top", "whole", "king", "space", "heard", "best",
  "hour", "better", "during", "hundred", "five", "remember", "step",
  "early", "hold", "west", "ground", "interest", "reach", "fast",
  "verb", "sing", "listen", "six", "table", "travel", "less", "morning",
  "ten", "simple", "several", "vowel", "toward", "war", "lay", "against",
  "pattern", "slow", "center", "love", "person", "money", "serve",
  "appear", "road", "map", "rain", "rule", "govern", "pull", "cold",
  "notice", "voice", "unit", "power", "town", "fine", "drive", "fall",
  "lead", "cry", "dark", "machine", "note", "wait", "plan", "figure",
  "star", "box", "noun", "field", "rest", "correct", "able", "pound",
  "done", "beauty", "drive", "stood", "contain", "front", "teach",
  "week", "final", "gave", "green", "oh", "quick", "develop", "ocean",
  "warm", "free", "minute", "strong", "special", "mind", "behind",
  "clear", "tail", "produce", "fact", "street", "inch", "lot", "nothing",
  "course", "stay", "wheel", "full", "force", "blue", "object", "decide",
  "surface", "deep", "moon", "island", "foot", "system", "busy", "test",
  "record", "boat", "common", "gold", "possible", "plane", "stead",
  "dry", "wonder", "laugh", "thousand", "ago", "ran", "check", "game",
  "shape", "equate", "hot", "miss", "brought", "heat", "snow", "tire",
  "bring", "yes", "distant", "fill", "east", "paint", "language", "among",
  "grand", "ball", "yet", "wave", "drop", "heart", "am", "present",
  "heavy", "dance", "engine", "position", "arm", "wide", "sail", "material",
  "size", "vary", "settle", "speak", "weight", "general", "ice", "matter",
  "circle", "pair", "include", "divide", "syllable", "felt", "perhaps",
  "pick", "sudden", "count", "square", "reason", "length", "represent",
  "art", "subject", "region", "energy", "hunt", "probable", "bed",
  "brother", "egg", "ride", "cell", "believe", "fraction", "forest",
  "sit", "race", "window", "store", "summer", "train", "sleep", "prove",
  "lone", "leg", "exercise", "wall", "catch", "mount", "wish", "sky",
  "board", "joy", "winter", "sat", "written", "wild", "instrument",
  "kept", "glass", "grass", "cow", "job", "edge", "sign", "visit",
  "past", "soft", "fun", "bright", "gas", "weather", "month", "million",
  "bear", "finish", "happy", "hope", "flower", "clothe", "strange",
  "gone", "jump", "baby", "eight", "village", "meet", "root", "buy",
  "raise", "solve", "metal", "whether", "push", "seven", "paragraph",
  "third", "shall", "held", "hair", "describe", "cook", "floor", "either",
  "result", "burn", "hill", "safe", "cat", "century", "consider", "type",
  "law", "bit", "coast", "copy", "phrase", "silent", "tall", "sand",
  "soil", "roll", "temperature", "finger", "industry", "value", "fight",
  "lie", "beat", "excite", "natural", "view", "sense", "ear", "else",
  "quite", "broke", "case", "middle", "kill", "son", "lake", "moment",
  "scale", "loud", "spring", "observe", "child", "straight", "consonant",
  "nation", "dictionary", "milk", "speed", "method", "organ", "pay",
  "age", "section", "dress", "cloud", "surprise", "quiet", "stone",
  "tiny", "climb", "cool", "design", "poor", "lot", "experiment",
  "bottom", "key", "iron", "single", "stick", "flat", "twenty",
  "skin", "smile", "crease", "hole", "trade", "melody", "trip", "office",
  "receive", "row", "mouth", "exact", "symbol", "die", "least", "trouble",
  "shout", "except", "wrote", "seed", "tone", "join", "suggest", "clean",
  "break", "lady", "yard", "rise", "bad", "blow", "oil", "blood",
  "touch", "grew", "cent", "mix", "team", "wire", "cost", "lost",
  "brown", "wear", "garden", "equal", "sent", "choose", "fell", "fit",
  "flow", "fair", "bank", "collect", "save", "control", "decimal",
  "gentle", "woman", "captain", "practice", "separate", "difficult",
  "doctor", "please", "protect", "noon", "whose", "locate", "ring",
  "character", "insect", "caught", "period", "indicate", "radio", "spoke",
  "atom", "human", "history", "effect", "electric", "expect", "crop",
  "modern", "element", "hit", "student", "corner", "party", "supply",
  "bone", "rail", "imagine", "provide", "agree", "thus", "capital",
  "wont", "chair", "danger", "fruit", "rich", "thick", "soldier",
  "process", "operate", "guess", "necessary", "sharp", "wing", "create",
  "neighbor", "wash", "bat", "rather", "crowd", "corn", "compare",
  "poem", "string", "bell", "depend", "meat", "rub", "tube", "famous",
  "dollar", "stream", "fear", "sight", "thin", "triangle", "planet",
  "hurry", "chief", "colony", "clock", "mine", "tie", "enter", "major",
  "fresh", "search", "send", "yellow", "gun", "allow", "print", "dead",
  "spot", "desert", "suit", "current", "lift", "rose", "continue",
  "block", "chart", "hat", "sell", "success", "company", "subtract",
  "event", "particular", "deal", "swim", "term", "opposite", "wife",
  "shoe", "shoulder", "spread", "arrange", "camp", "invent", "cotton",
  "born", "determine", "quart", "nine", "truck", "noise", "level",
  "chance", "gather", "shop", "stretch", "throw", "shine", "property",
  "column", "molecule", "select", "wrong", "gray", "repeat", "require",
  "broad", "prepare", "salt", "nose", "plural", "anger", "claim",
];

export const ABUSIVE_WORDS = [
  "ass", "arse", "asshole", "arsehole", "asshat", "asswipe", "asshole",
  "bastard", "bitch", "bitches", "bullshit", "crap", "damn", "dick", "douche",
  "douchebag", "fag", "faggot", "fuck", "fucking", "fucked", "fucker", "fuckers",
  "fucks", "motherfucker", "motherfuckers", "shit", "shits", "shitty", "cunt",
  "pussy", "cock", "prick", "twat", "wanker", "bollocks", "bloody", "bugger",
  "hell", "piss", "pissed", "slut", "whore", "nigga", "nigger", "retard", "retarded",
  "spic", "chink", "kike", "coon", "jap", "dyke", "tranny", "trannie", "queer", "homo",
  "poof", "poofter", "arsewipe", "assbag", "assbandit", "assclown", "assface", "asshole",
  "assmunch", "asswipe", "ballbag", "balls", "ballsack", "bastard", "beastiality", "blowjob",
  "boner", "boob", "boobs", "buttplug", "clit", "clitoris", "cock", "cocksucker", "cocksuck",
  "cum", "cummer", "cumming", "cums", "cumshot", "cunt", "damn", "dick", "dickhead", "dildo", "dyke",
  "fag", "faggot", "fags", "fanny", "fart", "fuck", "fucked", "fucker", "fuckface", "fuckhead",
  "fucking", "fuckoff", "fucks", "gangbang", "gay", "goddamn", "hell", "homo", "horny", "jizz",
  "jizzed", "knob", "labia", "minger", "motherfucker", "muff", "nazi", "nigga", "nigger", "orgasm",
  "penis", "piss", "pissed", "poop", "porn", "prick", "pube", "pussy", "queer", "rape", "retard",
  "rimjob", "scrotum", "semen", "sex", "shit", "shite", "shithead", "shitting", "shitty", "skank",
  "slag", "slut", "spastic", "spic", "suck", "tit", "tits", "titties", "tosser", "turd", "twat", "vagina",
  "wank", "wanker", "whore", "wtf", "xxx", "fuk", "fck", "fuking", "fukin", "shithead", "asswhole",
  "biatch", "bithc", "mofo", "mtherfcker", "mthrfcker", "n1gga", "niga", "sh1t", "sh1thead"
];

export const THAROOR = [
  "aberration", "abnegation", "abstemious", "acquiesce", "acrimony",
  "adulation", "aesthetic", "alacrity", "ameliorate", "anachronism",
  "anathema", "antediluvian", "antipathy", "apocryphal", "approbation",
  "arcane", "arduous", "articulate", "aspersion", "assiduous",
  "austere", "avarice", "baleful", "bellicose", "benevolent",
  "blandishment", "bombastic", "boorish", "cacophony", "cajole",
  "callous", "candor", "capricious", "castigate", "catharsis",
  "caustic", "chicanery", "circumspect", "clandestine", "cogent",
  "commensurate", "compendium", "complacent", "conflagration", "connoisseur",
  "conscientious", "consequential", "consternation", "contentious", "convivial",
  "copious", "corroborate", "credulous", "cursory", "dearth",
  "debacle", "decorum", "deleterious", "demagogue", "denouement",
  "deprecate", "derivative", "desultory", "diaphanous", "didactic",
  "diffident", "dilatory", "discerning", "disparate", "dispassionate",
  "dogmatic", "ebullient", "eclectic", "effervescent", "efficacy",
  "egregious", "elucidate", "emollient", "empirical", "enervate",
  "enigma", "ephemeral", "equanimity", "equivocal", "erudite",
  "esoteric", "euphemism", "exacerbate", "exculpate", "exigent",
  "expedient", "extol", "facetious", "fallacious", "fastidious",
  "fatuous", "felicitous", "florid", "fortuitous", "frivolous",
  "garrulous", "grandiloquent", "gregarious", "hackneyed", "halcyon",
  "harangue", "hedonistic", "heretical", "iconoclast", "idiosyncratic",
  "ignominious", "imbroglio", "impecunious", "imperious", "impertinent",
  "implacable", "impugn", "inchoate", "incisive", "incontrovertible",
  "indefatigable", "indolent", "ineffable", "inexorable", "ingenuous",
  "inscrutable", "insidious", "insipid", "intrepid", "intransigent",
  "invective", "irascible", "irrefutable", "jejune", "judicious",
  "juxtaposition", "kaleidoscopic", "lachrymose", "laconic", "largesse",
  "legerdemain", "loquacious", "lucid", "lugubrious", "magnanimous",
  "malediction", "mellifluous", "meticulous", "misanthrope", "mitigate",
  "modicum", "mollify", "moribund", "munificent", "nebulous",
  "nefarious", "neophyte", "obdurate", "obfuscate", "obsequious",
  "obstreperous", "officious", "ominous", "onerous", "opprobrium",
  "ostentatious", "parsimonious", "pejorative", "penchant", "penurious",
  "perfunctory", "pernicious", "perspicacious", "pertinacious", "phlegmatic",
  "platitude", "plethora", "ponderous", "precipitous", "predilection",
  "preponderance", "prescient", "proclivity", "prodigious", "profligate",
  "propensity", "propitious", "prosaic", "protean", "prudent",
  "pugnacious", "quagmire", "quintessential", "quixotic", "raconteur",
  "recalcitrant", "redoubtable", "refulgent", "reprobate", "rescind",
  "resolute", "reticent", "rhetoric", "salient", "sanctimonious",
  "sanguine", "sapient", "sardonic", "scintillating", "scrupulous",
  "serendipity", "solicitous", "sophistry", "spurious", "staunch",
  "stentorian", "stoic", "strident", "supercilious", "surreptitious",
  "sycophant", "taciturn", "tantamount", "tenacious", "tenuous",
  "timorous", "tirade", "torpid", "trenchant", "ubiquitous",
  "unctuous", "unfathomable", "untenable", "urbane", "usurp",
  "vacuous", "venerate", "veracity", "verbose", "verdant",
  "verisimilitude", "vicissitude", "vilify", "vindicate", "vociferous",
  "voracious", "wanton", "wistful", "zealous"
];

export const POTTER_HEAD = [
  "hogwarts", "gryffindor", "slytherin", "ravenclaw", "hufflepuff",
  "dumbledore", "voldemort", "snape", "hermione", "ron",
  "hagrid", "draco", "malfoy", "mcgonagall", "sirius",
  "lupin", "bellatrix", "neville", "ginny", "fred",
  "george", "dobby", "kreacher", "fawkes", "buckbeak",
  "hedwig", "moody", "umbridge", "slughorn", "quirrell",
  "diagon", "knockturn", "hogsmeade", "azkaban", "ministry",
  "platform", "privet", "godric", "forbidden", "chamber",
  "horcrux", "pensieve", "portkey", "time-turner", "remembrall",
  "howler", "sneakoscope", "omnious", "deluminator", "marauders",
  "map", "wand", "broomstick", "firebolt", "nimbus",
  "cloak", "stone", "cup", "diadem", "locket",
  "sorting", "hat", "owl", "patronus", "quidditch",
  "seeker", "keeper", "beater", "bludger", "snitch",
  "galleon", "sickle", "knut", "butterbeer", "pumpkin",
  "juice", "polyjuice", "felix", "veritaserum", "amortentia",
  "accio", "alohomora", "lumos", "nox", "expelliarmus",
  "stupefy", "protego", "reparo", "obliviate", "sectumsempra",
  "crucio", "imperio", "avada", "kedavra", "expecto",
  "patronum", "wingardium", "leviosa", "riddikulus", "finite",
  "incantatem", "confundo", "bombarda", "diffindo", "engorgio",
  "reducto", "aguamenti", "incendio", "tarantallegra", "silencio",
  "dragon", "hippogriff", "basilisk", "dementor", "boggart",
  "thestral", "acromantula", "phoenix", "werewolf", "giant",
  "house-elf", "centaur", "mermaid", "grindylow", "niffler",
  "flobberworm", "blast-ended", "skrewt", "cornish", "pixie",
  "triwizard", "tournament", "yule", "ball", "prophecy",
  "order", "phoenix", "deathly", "hallows", "elder",
  "resurrection", "invisibility", "horace", "tom", "riddle",
  "weasley", "longbottom", "lovegood", "diggory", "karkaroff",
  "maxime", "gringotts", "vault", "goblin", "keeper",
  "auror", "muggle", "squib", "pureblood", "half-blood",
  "mudblood", "wizard", "witch", "spell", "charm",
  "curse", "jinx", "transfiguration", "potions", "defense",
  "herbology", "arithmancy", "divination", "care", "magical",
  "creatures", "library", "common", "room", "great",
  "hall", "feast", "detention", "prefect", "headmaster"
];

function getRandomWordsFromList(list: string[], count: number): string[] {
  const shuffled = [...list].sort(() => Math.random() - 0.5);
  const result: string[] = [];
  while (result.length < count) result.push(...shuffled);
  return result.slice(0, count);
}

export function getWordsByLanguage(language: Language, count: number): string[] {
  switch (language) {
    case 'code':
      return getRandomWordsFromList(CODE_WORDS, count);
    case 'quotes': {
      const quoteWords = QUOTES.flatMap(quote => quote.split(' '));
      return getRandomWordsFromList(quoteWords, count);
    }
    case 'abusive':
      return getRandomWordsFromList(ABUSIVE_WORDS, count);
    case 'tharoor':
      return getRandomWordsFromList(THAROOR, count);
    case 'potter-head':
     return getRandomWordsFromList(POTTER_HEAD, count);
    default:
      return getRandomWordsFromList(WORD_LIST, count);
  }
}

// QWERTY finger mapping
export const FINGER_MAP: Record<string, string> = {
  // Left pinky
  q: 'left-pinky', a: 'left-pinky', z: 'left-pinky',
  '1': 'left-pinky', '`': 'left-pinky',
  // Left ring
  w: 'left-ring', s: 'left-ring', x: 'left-ring', '2': 'left-ring',
  // Left middle
  e: 'left-middle', d: 'left-middle', c: 'left-middle', '3': 'left-middle',
  // Left index
  r: 'left-index', f: 'left-index', v: 'left-index',
  t: 'left-index', g: 'left-index', b: 'left-index',
  '4': 'left-index', '5': 'left-index',
  // Right index
  y: 'right-index', h: 'right-index', n: 'right-index',
  u: 'right-index', j: 'right-index', m: 'right-index',
  '6': 'right-index', '7': 'right-index',
  // Right middle
  i: 'right-middle', k: 'right-middle', ',': 'right-middle', '8': 'right-middle',
  // Right ring
  o: 'right-ring', l: 'right-ring', '.': 'right-ring', '9': 'right-ring',
  // Right pinky
  p: 'right-pinky', ';': 'right-pinky', '/': 'right-pinky',
  "'": 'right-pinky', '0': 'right-pinky', '-': 'right-pinky',
  '=': 'right-pinky', '[': 'right-pinky', ']': 'right-pinky',
  '\\': 'right-pinky',
  // Thumbs
  ' ': 'thumb',
};

export const FINGER_LABELS: Record<string, string> = {
  'left-pinky': 'Left Pinky',
  'left-ring': 'Left Ring',
  'left-middle': 'Left Middle',
  'left-index': 'Left Index',
  'right-index': 'Right Index',
  'right-middle': 'Right Middle',
  'right-ring': 'Right Ring',
  'right-pinky': 'Right Pinky',
  'thumb': 'Thumb',
};
